import type { Achievement, LeaderboardEntry, Reward, StudyStreak, LevelSystem } from "@/types/gamification"

export const achievements: Achievement[] = [
  // Academic Achievements
  {
    id: "first-test",
    name: "First Steps",
    description: "Complete your first mock test",
    icon: "🎯",
    color: "bg-green-500",
    category: "milestone",
    rarity: "common",
    points: 50,
    requirements: [{ type: "tests_completed", value: 1 }],
    unlockedAt: new Date("2024-01-15"),
    progress: 100,
  },
  {
    id: "math-wizard",
    name: "Math Wizard",
    description: "Score 90% or higher in 5 math tests",
    icon: "🧙‍♂️",
    color: "bg-blue-500",
    category: "academic",
    rarity: "rare",
    points: 200,
    requirements: [
      { type: "test_score", value: 90, subject: "maths" },
      { type: "tests_completed", value: 5, subject: "maths" },
    ],
    unlockedAt: new Date("2024-01-20"),
    progress: 100,
  },
  {
    id: "streak-master",
    name: "Streak Master",
    description: "Maintain a 7-day study streak",
    icon: "🔥",
    color: "bg-red-500",
    category: "streak",
    rarity: "rare",
    points: 150,
    requirements: [{ type: "streak_days", value: 7 }],
    unlockedAt: new Date("2024-01-25"),
    progress: 100,
  },
  {
    id: "speed-reader",
    name: "Speed Reader",
    description: "Complete an English test in under 20 minutes",
    icon: "⚡",
    color: "bg-yellow-500",
    category: "academic",
    rarity: "rare",
    points: 100,
    requirements: [{ type: "time_spent", value: 20, subject: "english" }],
    progress: 75,
  },
  {
    id: "logic-master",
    name: "Logic Master",
    description: "Perfect score in 3 reasoning tests",
    icon: "🎓",
    color: "bg-purple-500",
    category: "academic",
    rarity: "epic",
    points: 300,
    requirements: [
      { type: "test_score", value: 100, subject: "reasoning" },
      { type: "tests_completed", value: 3, subject: "reasoning" },
    ],
    progress: 33,
  },
  {
    id: "century-club",
    name: "Century Club",
    description: "Complete 100 practice tests",
    icon: "💯",
    color: "bg-indigo-500",
    category: "milestone",
    rarity: "legendary",
    points: 500,
    requirements: [{ type: "tests_completed", value: 100 }],
    progress: 15,
  },
  {
    id: "all-rounder",
    name: "All-Rounder",
    description: "Score 80%+ in all subjects",
    icon: "🌟",
    color: "bg-pink-500",
    category: "academic",
    rarity: "epic",
    points: 400,
    requirements: [
      { type: "test_score", value: 80, subject: "maths" },
      { type: "test_score", value: 80, subject: "english" },
      { type: "test_score", value: 80, subject: "reasoning" },
      { type: "test_score", value: 80, subject: "science" },
    ],
    progress: 75,
  },
  {
    id: "marathon-runner",
    name: "Marathon Runner",
    description: "Study for 30 days straight",
    icon: "🏃‍♂️",
    color: "bg-orange-500",
    category: "streak",
    rarity: "legendary",
    points: 1000,
    requirements: [{ type: "streak_days", value: 30 }],
    progress: 40,
  },
]

export const mockLeaderboard: LeaderboardEntry[] = [
  {
    id: "1",
    studentId: "student-1",
    studentName: "Alex Johnson",
    avatar: "/placeholder.svg?height=40&width=40",
    points: 2750,
    level: 8,
    rank: 1,
    weeklyPoints: 450,
    monthlyPoints: 1200,
    badges: 12,
    streak: 15,
  },
  {
    id: "2",
    studentId: "student-2",
    studentName: "Emma Wilson",
    avatar: "/placeholder.svg?height=40&width=40",
    points: 2650,
    level: 7,
    rank: 2,
    weeklyPoints: 380,
    monthlyPoints: 1100,
    badges: 10,
    streak: 12,
  },
  {
    id: "3",
    studentId: "student-3",
    studentName: "Oliver Brown",
    avatar: "/placeholder.svg?height=40&width=40",
    points: 2500,
    level: 7,
    rank: 3,
    weeklyPoints: 420,
    monthlyPoints: 950,
    badges: 11,
    streak: 8,
  },
  {
    id: "4",
    studentId: "student-4",
    studentName: "Sophie Davis",
    avatar: "/placeholder.svg?height=40&width=40",
    points: 2350,
    level: 6,
    rank: 4,
    weeklyPoints: 290,
    monthlyPoints: 890,
    badges: 9,
    streak: 20,
  },
  {
    id: "5",
    studentId: "student-5",
    studentName: "James Miller",
    avatar: "/placeholder.svg?height=40&width=40",
    points: 2200,
    level: 6,
    rank: 5,
    weeklyPoints: 350,
    monthlyPoints: 800,
    badges: 8,
    streak: 5,
  },
]

export const rewards: Reward[] = [
  {
    id: "golden-badge",
    name: "Golden Star Badge",
    description: "Show off your achievements with this premium badge",
    icon: "⭐",
    type: "badge",
    cost: 500,
    category: "cosmetic",
    isUnlocked: true,
    isPurchased: false,
  },
  {
    id: "study-master-title",
    name: "Study Master Title",
    description: 'Unlock the prestigious "Study Master" title',
    icon: "👑",
    type: "title",
    cost: 1000,
    category: "title",
    isUnlocked: true,
    isPurchased: false,
  },
  {
    id: "dark-theme",
    name: "Dark Theme",
    description: "Unlock the sleek dark theme for your dashboard",
    icon: "🌙",
    type: "theme",
    cost: 300,
    category: "theme",
    isUnlocked: true,
    isPurchased: true,
  },
  {
    id: "custom-avatar",
    name: "Custom Avatar Frame",
    description: "Personalize your profile with a custom avatar frame",
    icon: "🖼️",
    type: "avatar",
    cost: 750,
    category: "cosmetic",
    isUnlocked: false,
    isPurchased: false,
  },
]

export const mockStudyStreak: StudyStreak = {
  currentStreak: 12,
  longestStreak: 18,
  lastActivityDate: new Date(),
  streakHistory: [
    { date: new Date("2024-01-28"), testsCompleted: 2, timeSpent: 45 },
    { date: new Date("2024-01-27"), testsCompleted: 1, timeSpent: 30 },
    { date: new Date("2024-01-26"), testsCompleted: 3, timeSpent: 60 },
    { date: new Date("2024-01-25"), testsCompleted: 1, timeSpent: 25 },
    { date: new Date("2024-01-24"), testsCompleted: 2, timeSpent: 40 },
  ],
}

export const mockLevelSystem: LevelSystem = {
  currentLevel: 8,
  currentXP: 1250,
  xpToNextLevel: 1500,
  totalXP: 2750,
  levelBenefits: [
    { level: 1, benefits: ["Access to basic tests"] },
    { level: 2, benefits: ["Unlock streak tracking"] },
    { level: 3, benefits: ["Access to medium difficulty tests"] },
    { level: 5, benefits: ["Unlock leaderboards"] },
    { level: 7, benefits: ["Access to hard difficulty tests"] },
    { level: 10, benefits: ["Unlock adaptive testing"] },
    { level: 15, benefits: ["Premium badge collection"] },
    { level: 20, benefits: ["Custom themes and avatars"] },
  ],
}
