import type { TeacherStudent, StudentProgress, ClassAnalytics, TestCreation } from "@/types/teacher"

export const mockTeacherStudents: TeacherStudent[] = [
  {
    id: "student-1",
    name: "Alex Johnson",
    email: "alex.johnson@email.com",
    avatar: "/placeholder.svg?height=40&width=40",
    grade: "Year 6",
    enrolledDate: new Date("2024-01-01"),
    lastActive: new Date("2024-01-28"),
    overallAverage: 85,
    testsCompleted: 24,
    currentStreak: 12,
    subjects: ["maths", "english", "reasoning", "science"],
    status: "active",
  },
  {
    id: "student-2",
    name: "Emma Wilson",
    email: "emma.wilson@email.com",
    avatar: "/placeholder.svg?height=40&width=40",
    grade: "Year 6",
    enrolledDate: new Date("2024-01-01"),
    lastActive: new Date("2024-01-27"),
    overallAverage: 92,
    testsCompleted: 28,
    currentStreak: 15,
    subjects: ["maths", "english", "reasoning", "science"],
    status: "active",
  },
  {
    id: "student-3",
    name: "Oliver Brown",
    email: "oliver.brown@email.com",
    avatar: "/placeholder.svg?height=40&width=40",
    grade: "Year 6",
    enrolledDate: new Date("2024-01-01"),
    lastActive: new Date("2024-01-25"),
    overallAverage: 68,
    testsCompleted: 15,
    currentStreak: 3,
    subjects: ["maths", "english", "reasoning"],
    status: "needs_attention",
  },
  {
    id: "student-4",
    name: "Sophie Davis",
    email: "sophie.davis@email.com",
    avatar: "/placeholder.svg?height=40&width=40",
    grade: "Year 5",
    enrolledDate: new Date("2024-01-01"),
    lastActive: new Date("2024-01-28"),
    overallAverage: 78,
    testsCompleted: 20,
    currentStreak: 8,
    subjects: ["maths", "english", "reasoning", "science"],
    status: "active",
  },
  {
    id: "student-5",
    name: "James Miller",
    email: "james.miller@email.com",
    avatar: "/placeholder.svg?height=40&width=40",
    grade: "Year 5",
    enrolledDate: new Date("2024-01-01"),
    lastActive: new Date("2024-01-20"),
    overallAverage: 72,
    testsCompleted: 18,
    currentStreak: 0,
    subjects: ["maths", "english", "reasoning"],
    status: "inactive",
  },
]

export const mockClassAnalytics: ClassAnalytics = {
  totalStudents: 5,
  activeStudents: 3,
  averageClassScore: 79,
  totalTestsCompleted: 105,
  subjectPerformance: [
    {
      subject: "maths",
      averageScore: 82,
      studentsCount: 5,
      testsCompleted: 35,
    },
    {
      subject: "english",
      averageScore: 85,
      studentsCount: 5,
      testsCompleted: 30,
    },
    {
      subject: "reasoning",
      averageScore: 75,
      studentsCount: 5,
      testsCompleted: 25,
    },
    {
      subject: "science",
      averageScore: 80,
      studentsCount: 3,
      testsCompleted: 15,
    },
  ],
  topPerformers: [
    { studentId: "student-2", studentName: "Emma Wilson", score: 92 },
    { studentId: "student-1", studentName: "Alex Johnson", score: 85 },
    { studentId: "student-4", studentName: "Sophie Davis", score: 78 },
  ],
  needsAttention: [
    {
      studentId: "student-3",
      studentName: "Oliver Brown",
      reason: "Below average performance (68%)",
      priority: "high",
    },
    {
      studentId: "student-5",
      studentName: "James Miller",
      reason: "Inactive for 8 days",
      priority: "medium",
    },
  ],
}

export const mockStudentProgress: StudentProgress[] = [
  {
    studentId: "student-1",
    studentName: "Alex Johnson",
    recentTests: [
      {
        testId: "test-1",
        testName: "Arithmetic Fundamentals",
        subject: "maths",
        score: 85,
        maxScore: 100,
        percentage: 85,
        completedAt: new Date("2024-01-28"),
        timeSpent: 45,
      },
      {
        testId: "test-2",
        testName: "Reading Comprehension",
        subject: "english",
        score: 92,
        maxScore: 100,
        percentage: 92,
        completedAt: new Date("2024-01-27"),
        timeSpent: 38,
      },
    ],
    subjectPerformance: [
      {
        subject: "maths",
        average: 85,
        testsCompleted: 8,
        trend: "improving",
        lastTestDate: new Date("2024-01-28"),
      },
      {
        subject: "english",
        average: 88,
        testsCompleted: 6,
        trend: "stable",
        lastTestDate: new Date("2024-01-27"),
      },
    ],
    weeklyActivity: [
      { week: "Week 1", testsCompleted: 3, averageScore: 78, studyTime: 120 },
      { week: "Week 2", testsCompleted: 5, averageScore: 82, studyTime: 150 },
      { week: "Week 3", testsCompleted: 4, averageScore: 85, studyTime: 180 },
      { week: "Week 4", testsCompleted: 3, averageScore: 88, studyTime: 160 },
    ],
  },
]

export const mockTestTemplates: TestCreation[] = [
  {
    id: "test-template-1",
    title: "Year 6 Mathematics Assessment",
    description: "Comprehensive math test covering arithmetic, fractions, and basic algebra",
    subject: "maths",
    difficulty: "medium",
    duration: 45,
    totalQuestions: 20,
    passingScore: 70,
    isAdaptive: false,
    tags: ["arithmetic", "fractions", "algebra"],
    questions: [
      {
        id: "q1",
        type: "multiple-choice",
        question: "What is 15 + 27?",
        options: ["40", "42", "44", "46"],
        correctAnswer: "42",
        explanation: "15 + 27 = 42",
        points: 1,
        timeLimit: 60,
      },
    ],
    assignedTo: ["student-1", "student-2"],
    dueDate: new Date("2024-02-15"),
    status: "published",
  },
  {
    id: "test-template-2",
    title: "English Comprehension Practice",
    description: "Reading comprehension and grammar skills assessment",
    subject: "english",
    difficulty: "medium",
    duration: 40,
    totalQuestions: 15,
    passingScore: 75,
    isAdaptive: true,
    tags: ["reading", "grammar", "comprehension"],
    questions: [
      {
        id: "q1",
        type: "multiple-choice",
        question: 'Which word is a synonym for "happy"?',
        options: ["Sad", "Joyful", "Angry", "Tired"],
        correctAnswer: "Joyful",
        explanation: "Joyful means feeling great pleasure and happiness",
        points: 1,
        timeLimit: 45,
      },
    ],
    assignedTo: [],
    status: "draft",
  },
]
