import type { Question, TestTemplate } from "@/types/test"

export const sampleQuestions: Question[] = [
  // Mathematics Questions
  {
    id: "math-001",
    type: "multiple-choice",
    subject: "maths",
    difficulty: "easy",
    question: "What is 15 + 27?",
    options: ["40", "42", "44", "46"],
    correctAnswer: "42",
    explanation:
      "15 + 27 = 42. Add the ones place: 5 + 7 = 12, write 2 and carry 1. Add the tens place: 1 + 2 + 1 = 4.",
    points: 1,
    timeLimit: 60,
  },
  {
    id: "math-002",
    type: "multiple-choice",
    subject: "maths",
    difficulty: "medium",
    question: "If a rectangle has a length of 8cm and width of 5cm, what is its area?",
    options: ["13 cm²", "26 cm²", "40 cm²", "45 cm²"],
    correctAnswer: "40 cm²",
    explanation: "Area of rectangle = length × width = 8 × 5 = 40 cm²",
    points: 2,
    timeLimit: 90,
  },
  {
    id: "math-003",
    type: "multiple-choice",
    subject: "maths",
    difficulty: "hard",
    question: "What is the value of x in the equation: 3x + 7 = 22?",
    options: ["3", "5", "7", "9"],
    correctAnswer: "5",
    explanation: "3x + 7 = 22, so 3x = 22 - 7 = 15, therefore x = 15 ÷ 3 = 5",
    points: 3,
    timeLimit: 120,
  },

  // English Questions
  {
    id: "eng-001",
    type: "multiple-choice",
    subject: "english",
    difficulty: "easy",
    question: 'Which word is a synonym for "happy"?',
    options: ["Sad", "Joyful", "Angry", "Tired"],
    correctAnswer: "Joyful",
    explanation: "Joyful means feeling great pleasure and happiness, making it a synonym for happy.",
    points: 1,
    timeLimit: 45,
  },
  {
    id: "eng-002",
    type: "multiple-choice",
    subject: "english",
    difficulty: "medium",
    question: "Identify the correct sentence:",
    options: [
      "The children was playing in the park.",
      "The children were playing in the park.",
      "The children is playing in the park.",
      "The children are play in the park.",
    ],
    correctAnswer: "The children were playing in the park.",
    explanation:
      '"Children" is plural, so it requires the plural verb "were" and the past continuous tense "were playing".',
    points: 2,
    timeLimit: 60,
  },

  // Reasoning Questions
  {
    id: "reason-001",
    type: "multiple-choice",
    subject: "reasoning",
    difficulty: "easy",
    question: "What comes next in the sequence: 2, 4, 6, 8, ?",
    options: ["9", "10", "11", "12"],
    correctAnswer: "10",
    explanation: "This is a sequence of even numbers increasing by 2 each time: 2, 4, 6, 8, 10.",
    points: 1,
    timeLimit: 60,
  },
  {
    id: "reason-002",
    type: "multiple-choice",
    subject: "reasoning",
    difficulty: "medium",
    question: "If all roses are flowers, and some flowers are red, which statement must be true?",
    options: ["All roses are red", "Some roses are red", "All flowers are roses", "Some roses might be red"],
    correctAnswer: "Some roses might be red",
    explanation:
      "We know all roses are flowers, and some flowers are red, but we cannot conclude that roses specifically are red.",
    points: 2,
    timeLimit: 90,
  },

  // Science Questions
  {
    id: "sci-001",
    type: "multiple-choice",
    subject: "science",
    difficulty: "easy",
    question: "What do plants need to make their own food?",
    options: ["Water only", "Sunlight only", "Water, sunlight, and carbon dioxide", "Soil only"],
    correctAnswer: "Water, sunlight, and carbon dioxide",
    explanation: "Plants use photosynthesis to make food, which requires water, sunlight, and carbon dioxide.",
    points: 1,
    timeLimit: 60,
  },
  {
    id: "sci-002",
    type: "multiple-choice",
    subject: "science",
    difficulty: "medium",
    question: "Which of these is NOT a renewable energy source?",
    options: ["Solar power", "Wind power", "Coal", "Hydroelectric power"],
    correctAnswer: "Coal",
    explanation:
      "Coal is a fossil fuel that takes millions of years to form, making it non-renewable. Solar, wind, and hydroelectric are renewable.",
    points: 2,
    timeLimit: 75,
  },
]

export const testTemplates: TestTemplate[] = [
  {
    id: "math-basic",
    title: "Mathematics Fundamentals",
    description: "Test your basic arithmetic and problem-solving skills",
    subject: "maths",
    difficulty: "easy",
    duration: 30,
    totalQuestions: 10,
    passingScore: 70,
    questions: sampleQuestions.filter((q) => q.subject === "maths"),
    isAdaptive: false,
    tags: ["arithmetic", "basic", "fundamentals"],
  },
  {
    id: "eng-comprehension",
    title: "English Comprehension",
    description: "Reading comprehension and grammar skills assessment",
    subject: "english",
    difficulty: "medium",
    duration: 45,
    totalQuestions: 15,
    passingScore: 75,
    questions: sampleQuestions.filter((q) => q.subject === "english"),
    isAdaptive: true,
    tags: ["reading", "grammar", "comprehension"],
  },
  {
    id: "reasoning-logic",
    title: "Logical Reasoning",
    description: "Test your logical thinking and pattern recognition",
    subject: "reasoning",
    difficulty: "medium",
    duration: 40,
    totalQuestions: 12,
    passingScore: 70,
    questions: sampleQuestions.filter((q) => q.subject === "reasoning"),
    isAdaptive: true,
    tags: ["logic", "patterns", "critical-thinking"],
  },
  {
    id: "science-general",
    title: "General Science",
    description: "Basic science concepts and natural phenomena",
    subject: "science",
    difficulty: "easy",
    duration: 35,
    totalQuestions: 12,
    passingScore: 65,
    questions: sampleQuestions.filter((q) => q.subject === "science"),
    isAdaptive: false,
    tags: ["biology", "physics", "chemistry", "general"],
  },
]
